# Generated by Django 4.2.6 on 2023-10-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportfolio', '0002_pdfdocument1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
