# Generated by Django 4.2.6 on 2023-10-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userportfolio', '0004_project_skill_suggestedtechnology_delete_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
